import {
  ArrowRight,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  Copy,
  Download,
  Edit,
  ExternalLink,
  File,
  FileText,
  Filter,
  Folder,
  Github,
  GripVertical,
  ImageIcon,
  Laptop,
  Loader2,
  Mail,
  MessageSquare,
  MoreHorizontal,
  Plus,
  PlusCircle,
  Reply,
  Rocket,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  SidebarClose,
  SidebarOpen,
  Trash,
  User,
  X,
  XCircle,
} from "lucide-react";
import { FcGoogle } from "react-icons/fc";

export const Icons = {
  logo: Rocket,
  close: X,
  menu: MoreHorizontal,
  spinner: Loader2,
  github: Github,
  mail: Mail,
  arrowRight: ArrowRight,
  externalLink: ExternalLink,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  copy: Copy,
  trash: Trash,
  edit: Edit,
  check: Check,
  upload: Download,
  ImageIcon: ImageIcon,
  File: File,
  FileText: FileText,
  Folder: Folder,
  Filter: Filter,
  GripVertical: GripVertical,
  Laptop: Laptop,
  MessageSquare: MessageSquare,
  Plus: Plus,
  PlusCircle: PlusCircle,
  Reply: Reply,
  Search: Search,
  Send: Send,
  Server: Server,
  Settings: Settings,
  Share2: Share2,
  Shield: Shield,
  SidebarClose: SidebarClose,
  SidebarOpen: SidebarOpen,
  User: User,
  XCircle: XCircle,
  Circle: Circle,
  google: FcGoogle,
};
